name: pictoword
description: ...
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/themes/animaux.json
    - assets/themes/drapeaux.json
    - assets/themes/plantes.json
    - assets/themes/taekwondo.json
    - assets/themes/voitures.json

    - assets/wordpool/animaux_words.json
    - assets/wordpool/drapeaux_words.json
    - assets/wordpool/plantes_words.json
    - assets/wordpool/taekwondo_words.json
    - assets/wordpool/voitures_words.json

    - assets/images/animaux
    - assets/images/drapeaux
    - assets/images/plantes
    - assets/images/taekwondo
    - assets/images/voitures
